### ISSUE TITLE
Add support for adding and manipulating dependencies from the command line

### ISSUE THREAD

**Issue by kjjuno** [GitDepend/GitDepend#148]
Adding dependencies to GitDepend.json is currently manual. There should be a way to add a new dependency from the command line.

**Comment by pdubb29** [comment]
we need a way to identify certain dependencies. I'm thinking of adding a "id" property to the GitDepend.json file to easily point to which one you would like to update. Thoughts?

**Comment by kjjuno** [comment]
what about `gitdepend add -source https://github.com/GitDepend/Lib2.git -dir c:\git\Lib2`
