### ISSUE TITLE
update doesn't fail when nuget fails to update to the specified package

### ISSUE THREAD

**Issue by kjjuno** [GitDepend/GitDepend#169]
update should fail fast when nuget update fails to update to the specified version of a package. Right now that message gets lost in the noise,, and it's easy to not realize that there was a problem.

**Comment by pdubb29** [comment]
I'll start working on this one.

**Comment by kjjuno** [comment]
@pdubb29 it's all yours

**Comment by kjjuno** [comment]
The big problem here is that executing the nuget update command doesn't seem to return a non 0 error code. We will have to research methods of determining if nuget.exe failed to run correctly, and fail immediately if a package could not be updated.
