### ISSUE TITLE
update <name> does the wrong thing

### ISSUE THREAD

**Issue by kjjuno** [GitDepend/GitDepend#170]
specifying `GitDepend update <name>` is building the named repository, but does not update to the newly built packages.

**Comment by pdubb29** [comment]
I'll work on this one now.

**Comment by pdubb29** [comment]
Could this be related to the changes which I made to the `ExecuteNugetCommand()` in pr #174 on issue #169? Restore and Update both go through the same path.

**Comment by kjjuno** [comment]
It's possible. I haven't spent the time yet to debug why this happens. I just wanted to use this feature yesterday and it ran all the build scripts, but never updated the packages.
