### ISSUE TITLE
list should show more information

### ISSUE THREAD

**Issue by kjjuno** [GitDepend/GitDepend#173]
`GitDepend list` should display the following information

* the friendly name of dependencies (it is doing this).
* The referenced branch
* The currently checked out branch (there should be some visual indication when these are out of sync)
* The directory where that dependency exists on disk

**Comment by kjjuno** [comment]
current
```
- lib4
    - lib1
    - lib3
        - lib1
    - lib2
```

desired
```
- lib4 (develop)
  c:\sd\git\lib4

    - lb1 (develop)
      c:\sd\git\lib1

    - lib3 (develop)
      c:\sd\git\lib3

        - lib1 (develop)
          c:\sd\git\lib1

    - lib2 (develop)
      c:\sd\git\lib2
```

**Comment by kjjuno** [comment]
I'm not sure what the actual desired output here is. I just have the feeling that the list command could be so much better

**Comment by pdubb29** [comment]
I think the output you have listed looks pretty good.

**Comment by bbirds** [comment]
I'll work on this.

**Comment by bbirds** [comment]
Do we want to add this as an option, like a verbose mode, or just have it all of the time?
