### ISSUE TITLE
update should have a dry-run option

### ISSUE THREAD

**Issue by kjjuno** [GitDepend/GitDepend#191]
Similar to the work @pdubb29 did with the clean command, I would like a dry run option on update. This would make it easy to know what will happen if I run `GitDepend update` on my projects.

**Comment by bbirds** [comment]
I'm planning to take this on.

**Comment by pdubb29** [comment]
From what I was thinking, (and what @bbirds and I talked about) I was thinking of having the dry run option tell you what needs to build and what the version would be updated to.

If the build doesn't need to be updated in the dependencies, it should print out it doesn't need to be built. The output should look something similar to the list command with some details

RootProject
     Lib1 - Needs to be re-built, packages will be changed to v#
     Lib2 - Up to date

**Comment by pdubb29** [comment]
Or it can be similar to other of the visitors where it prints out the directory and the name and then gives the status on a new line. I think either approach would be appropriate.

**Comment by kjjuno** [comment]
@pdubb29 the only problem I see with your vision is the version piece. GitDepend currently has no idea of knowing what version will be produced when a build is run. We are blindly running the build script, and consuming packages that were produced. But, without building the packages we have no idea what the version is.

If we DID have a way to know the version ahead of time that would help this problem out a LOT. It would also make it easier to skip builds if the version that would be built is also available on the the nuget feeds.

**Comment by kjjuno** [comment]
I have added https://github.com/GitDepend/GitDepend/issues/236. This should give us the information necessary to accomplish what you have laid out.

**Comment by bbirds** [comment]
Here's something of a first draft output.
Branch Changes:
        All dependencies on the correct branch
Dependencies to build:
        core
        claims.estimate
Projects that would need to update:
        core
        claims.estimate
