### ISSUE TITLE
Treating Nuget WARNING as a fatal error causes git depend to fail when it should not

### ISSUE THREAD

**Issue by kjjuno** [GitDepend/GitDepend#192]
WARNINGS from Nuget are considered fatal errors in gitdepend. This is causing the update to fail when it should have succeeded.

**Comment by kjjuno** [comment]
So, we are updating nuget packages in whatever order we find them (probably alphabetical) when we find them in the artifacts directory. Nuget is complaining that dependency version requirements are not met. If we could figure out the lowest level dependency and update that first, and then work our way up the dependency tree that would probably help nuget not freak out.

**Comment by kjjuno** [comment]
I haven't seen this warning in a while, and I don't know what the reproduction steps are. For now, let's make sure we aren't aborting the update process because of warnings in nuget, and close this. (That may be done already).

We can re-open this if we start running into this.

**Comment by pdubb29** [comment]
Code has been removed to check for warnings.
