### ISSUE TITLE
Manage command deletes as opposed to updating (when project dependency doesn't exist)

### ISSUE THREAD

**Issue by pdubb29** [GitDepend/GitDepend#197]
I add a dependency (when the project dependency doesn't exist) using the following command

`dep add -u https://test.url.com/testproject -d ..\newproj -b develop`
The output is as I expect, with the GitDepend.json file changed.
```
"dependencies": [
    {
      "url": "https://test.url.com/testproject",
      "dir": "..\\newproj",
      "branch": "develop"
    }
  ]
```

I run the manage command to update the url:
`dep manage -u **https://test.url.com/testnewproject`

It deletes the dependency in the GitDepend.json file:
`"dependencies": []`

Expected Result: The Dependency should be edited with the new url.

What happened: Dependency was deleted.

**Comment by pdubb29** [comment]
This is also true for any argument passed to the manage command.

**Comment by pdubb29** [comment]
After doing some more testing, this could not be a bug, due to the fact that the manage command visits the dependency. If it doesn't find it, I think deleting it is a good idea. Thoughts @kjjuno?

**Comment by kjjuno** [comment]
I'm not sure yet. I haven't had a chance to play with this command yet. My gut feeling is that it feels like a bug to have the dependency deleted. That isn't what the user was trying to do. We could possibly warn that the dependency could not be found. The user could be presented with the option to delete at that point. 

I just think it feels bad to delete when that isn't what the user was trying to do

**Comment by pdubb29** [comment]
I've been testing this again.
if the directory doesn't exist, it doesn't delete the dependency, it first attempts to clone. If that doesn't work, then it fails to execute.

If the directory does exist then it will edit the config appropriately.

I'm thinking this could be a much smaller issue, not the original one.

Scenario: I've added a new dependency to my config file, but I got the url wrong. If i want to edit the url I don't want it to try to clone, I would just like it to edit. Problem is, this command asks for the friendly name rather than the directory. If it was a simple directory matching that would be possible. But since it needs the friendly name from the argument it needs to replicate this.

**Comment by kjjuno** [comment]
Thats an interesting problem, and I'm not sure what the solution is yet

**Comment by kjjuno** [comment]
I think the best thing we can do here is print an error describing why we can't continue and just fail to process. It's up to the user to manually fix things at that point.

Perhaps with a redesign we could do better, but with the current GitDepend.json format I don't see another option.

**Comment by pdubb29** [comment]
Unable to reproduce.
