### ISSUE TITLE
Handling non-initialized repos

### ISSUE THREAD

**Issue by bbirds** [GitDepend/GitDepend#225]
Updates get confused when one of the dependencies is not an initialized repository. Could this be fixed by the commands failing if one of the dependencies is not initialized?

**Comment by kjjuno** [comment]
Sounds very reasonable

**Comment by pdubb29** [comment]
We need the default implementation of the base visitor to be checking if the configuration exists. If the configuration does not exist, the default handling should fail and quit the process. It should be allowed to be overridden.
